module.exports = {
  //  'To kill myself':10,
  //  'Want to die right now':9,
  //  'To commit suicide ':11,
  //  'Have nothing to live for':12,
  //  'Want to kill ':13,
  //  'It’s not worth it anymore':40,
  //  'Can’t live ':40,
  //  'Don’t want to live anymore':12,
  //  'To end it ':12,
  //  'Me want to kill myself':1,
  //  'I’m tired of Myself ':12,
  //  'hate my life hate':14,
  //  'I hate myself':16,
  //  'Want to be here anymore':10,
  //  'End it all ':11,
  //  'Want it to be over':12,
  //  'End my life Want it all to end':12,
  //  'Take my own Wish':14,
  //  'could just fall asleep':15,
  //  'Kill myself and ':15,
  //  'Fall asleep and never wake':13,
  //  'My death would ':14,
  //  'Want to end it all':112,
  //  'To live anymore ':14,
  //  'Just really want to die':13,
  //  'About killing myself ':12,
  //  'Rather die its not worth':20,
  //  'Kill myself' :40,
  //  'I’m sorry that i m leaving':50,
  //  'Never wake up':50,
  //  'Fuck trying to live normal':50,
  //  'Killing myself i ':10,
  //  'So why should continue living':30,
  //  'Stop the pain ':10,
  // ' Don’t want to live defeated':10,
  //  'Kill myself right ':10,
  //  'To commit suicide within few':10,
  //  'Thoughts of suicide ':10,
  //  'And pain anymore just can':10,
  //  'Point in living ':10,
  //  'Put an end to this':10,
  //  'Worth it anymore ':10,
  //  'Been self harming for years':10,
  //  'Have nothing to ':10
  //  'Bad really am worthless what':10
  //  'Wanted to die ':10
  //  'Life is this miserable just':10
  
  };
  