module.exports = {
    'To_kill_myself':'98, red, yes',
    'Want_to_die_right_now':'92, red, yes',
    'To_commit_suicide':'99, red, yes',
    'Have_nothing_to_live_for':'83, red, yes',
    'Want_to_kill':'82, orange, yes',
    'It_not_worth_it_anymore': '63, yellow, yes',
    'Cant_live':'71, orange ,yes',
    'Dont_want_to_live_anymore': '77, red, yes',
    'To_end_it': '54, yellow, no',
    'I_am_tired_of_Myself':'85, orange, yes',
    'hate_my_life_hate':'73, orange, yes',
    'I_hate_myself': '69, orange, yes',
    'Want_to_be_here_anymore': '42, yellow, no',
    'End_it_all': '47, yellow, no',
    'Want_it_to_be_over': '70, orange, yes',
    'End_my_life_Want_it_all_to_end': '81, red, yes',
    'Take_my_own_Wish':' 53, yellow,no',
    'could_just_fall_asleep': '73, yellow, yes',
    'Fall_asleep_and_never_wake': '90, red, yes',
    'My_death_would': '79, orange ,yes',
    'Want_to_end_it_all':'47, yellow, no',
    'To_live_anymore': '54, yellow, no',
    'Just_really_want_to_die':'83, red, yes',
    'About_killing_myself': '86, red, yes',
    'Rather_die_its_not_worth': '82, red,yes',
    'I_am_sorry_that_i_m_leaving': '94, red, yes',
    'Never_wake_up':'70, orange, yes',
    'Fuck_trying_to_live_normal, 81, orange, yes',
    'So_why_should_continue_living, 90, red, yes',
      'Stop_the_pain': '66, yellow, no',
  'Dont_want_to_live_defeated':'37, yellow, no',
  'Want_to_kill':'82, orange, yes',
  'It_not_worth_it_anymore': '63, yellow, yes',
  'Cant_live':'71, orange ,yes',
  'Dont_want_to_live_anymore': '77, red, yes',
  'To_end_it': '54, yellow, no',
  'I_am_tired_of_Myself':'85, orange, yes',
  'hate_my_life_hate':'73, orange, yes',
  'I_hate_myself': '69, orange, yes',
  'Want_to_be_here_anymore': '42, yellow, no',
  'End_it_all': '47, yellow, no',
  'Want_it_to_be_over': '70, orange, yes',
  'End_my_life_Want_it_all_to_end': '81, red, yes',
  'Take_my_own_Wish':' 53, yellow,no',
  'could_just_fall_asleep': '73, yellow, yes',
  'Fall_asleep_and_never_wake': '90, red, yes',
  'My_death_would': '79, orange ,yes',
  'Want_to_end_it_all':'47, yellow, no',
  'Kill_myself_right, 82, red, yes',
   'commit_suicide_within_few,98, red, yes',
    'Thoughts_of_suicide, 96, red, yes',
    'Want_to_kill':'82, orange, yes',
    'It_not_worth_it_anymore': '63, yellow, yes',
    'Cant_live':'71, orange ,yes',
    'Dont_want_to_live_anymore': '77, red, yes',
    'To_end_it': '54, yellow, no',
    'I_am_tired_of_Myself':'85, orange, yes',
    'hate_my_life_hate':'73, orange, yes',
    'I_hate_myself': '69, orange, yes',
    'Want_to_be_here_anymore': '42, yellow, no',
    'End_it_all': '47, yellow, no',
    'Want_it_to_be_over': '70, orange, yes',
    'End_my_life_Want_it_all_to_end': '81, red, yes',
    'Take_my_own_Wish':' 53, yellow,no',
    'could_just_fall_asleep': '73, yellow, yes',
    'Fall_asleep_and_never_wake': '90, red, yes',
    'My_death_would': '79, orange ,yes',
    'Want_to_end_it_all':'47, yellow, no',
    'it_started_badly_and_it_will_end_worse':' 62, yellow, no',
    'It_not_worth_it_anymore': '63, yellow, yes',
    'Cant_live':'71, orange ,yes',
    'Dont_want_to_live_anymore': '77, red, yes',
    'To_end_it': '54, yellow, no',
    'I_am_tired_of_Myself':'85, orange, yes',
    'hate_my_life_hate':'73, orange, yes',
    'I_hate_myself': '69, orange, yes',
    'Want_to_be_here_anymore': '42, yellow, no',
    'End_it_all': '47, yellow, no',
    'Want_it_to_be_over': '70, orange, yes',
    'End_my_life_Want_it_all_to_end': '81, red, yes',
    'Take_my_own_Wish':' 53, yellow,no',
    'could_just_fall_asleep': '73, yellow, yes',
    'Fall_asleep_and_never_wake': '90, red, yes',
    'My_death_would': '79, orange ,yes',
    'Want_to_end_it_all':'47, yellow, no',
    'Existence_is_futile, 82, red, yes',
    'If_loneliness_was_friends_then_I_had_have_a_lot_of_friends, 76, orange, yes',
    'I_am_trapped_in_an_endless_loop_of_misery_and_regret_my_life, 90, red, yes',
    'I_had_a_near_death_experience_today_so_I_nearly_had_a_good_day, 92, red, yes',
    'Even_in_a_crowded_room_i_feel_lonely': '70, orange, yes',
    'live_rudely': '57, yellow, no'






};    